services:
  postgres:
    image: postgres:15
    container_name: studentapi-db
    environment:
      POSTGRES_DB: studentdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - postgres_student_data:/var/lib/postgresql/data
    networks:
      - studentapi-network

  app:
    image: furkan23/studentapi:latest
    container_name: studentapi-app
    ports:
      - "80:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/studentdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    depends_on:
      - postgres
    networks:
      - studentapi-network

networks:
  studentapi-network:
    driver: bridge

volumes:
  postgres_student_data: